#!/bin/bash

while [ 1 ] ; do
    pid=`ps ahux --sort=-c | grep squeezelite | awk '{if($3>70)print $2}'`
    if [ "$pid" != "" ] ; then
        sudo systemctl restart btspeaker-monitor
        exit
    else
        sleep 30s
    fi
done
